spring.application.name=SpringRESTCRUDProj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=Vinayreddy@7780

#spring.jpa.properties.hibernate.dialect=org.hibernate.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true